import type { Metadata } from "next";
import { Space_Grotesk, DM_Sans } from "next/font/google"
import "../globals.css";
import { BasicSidebar } from "@/components/basic-sidebar"
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar"

// const spaceGrotesk = Space_Grotesk({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-space-grotesk",
// })

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  // variable: "--font-dm-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.className} antialiased bg-red-600`}
      >
        <SidebarProvider>
          <BasicSidebar />
          <SidebarInset>
            {children}
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
